definitions:
  db.FileType:
    enum:
    - documentation
    - checklist
    - remarks
    - remarks_clustered
    - final_report
    type: string
    x-enum-varnames:
    - FileTypeDocumentation
    - FileTypeChecklist
    - FileTypeRemarks
    - FileTypeRemarksClustered
    - FileTypeFinalReport
  db.Project:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        $ref: '#/definitions/db.ProjectStatus'
    type: object
  db.ProjectFile:
    properties:
      extension:
        type: string
      file_path:
        type: string
      file_size:
        type: integer
      file_type:
        $ref: '#/definitions/db.FileType'
      filename:
        type: string
      id:
        type: integer
      original_name:
        type: string
      project_id:
        type: integer
      uploaded_at:
        type: string
    type: object
  db.ProjectStatus:
    enum:
    - ready
    - processing_remarks
    - processing_checklist
    - generating_final_report
    type: string
    x-enum-varnames:
    - ProjectStatusReady
    - ProjectStatusProcessingRemarks
    - ProjectStatusProcessingChecklist
    - ProjectStatusGeneratingFinalReport
  handler.Error:
    properties:
      error: {}
    type: object
  handler.Response:
    properties:
      body: {}
    type: object
  models.CreateProjectRequest:
    properties:
      name:
        maxLength: 255
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Проверка состояния сервиса и подключения к базе данных
      operationId: health
      produces:
      - application/json
      responses:
        "200":
          description: Service health status
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Health check
  /projects:
    get:
      consumes:
      - application/json
      description: Get list of all projects
      operationId: listProjects
      produces:
      - application/json
      responses:
        "200":
          description: List of projects
          schema:
            items:
              $ref: '#/definitions/db.Project'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get all projects
    post:
      consumes:
      - application/json
      description: Create a new project with name
      operationId: createProject
      parameters:
      - description: Project data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/models.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Project created successfully
          schema:
            $ref: '#/definitions/db.Project'
        "400":
          description: Bad request - invalid input data
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create new project
  /projects/{id}:
    get:
      consumes:
      - application/json
      description: Get specific project by its ID
      operationId: getProject
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Project found
          schema:
            $ref: '#/definitions/db.Project'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get project by ID
  /projects/{id}/checklist:
    get:
      consumes:
      - application/json
      description: Get checklist result for a specific project
      operationId: getChecklist
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Checklist result
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Checklist is still being generated
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get project checklist
    post:
      consumes:
      - application/json
      description: Generate checklist for a specific project
      operationId: generateChecklist
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Checklist generation started
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Project is not in ready status
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Generate checklist for project
  /projects/{id}/documentation:
    post:
      consumes:
      - multipart/form-data
      description: Upload a documentation file to a specific project (max 50MB)
      operationId: uploadDocumentation
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      - description: Documentation file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Documentation file uploaded successfully
          schema:
            $ref: '#/definitions/db.ProjectFile'
        "400":
          description: Bad request - invalid input data
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Project is not in ready status
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Upload documentation file to project
  /projects/{id}/final_report:
    get:
      consumes:
      - application/json
      description: Get final report result for a specific project
      operationId: getFinalReport
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Final report result
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Final report is still being generated
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get final report for project
    post:
      consumes:
      - application/json
      description: Generate final report for a specific project
      operationId: generateFinalReport
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Final report generation started
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Project is already being processed
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Generate final report for project
  /projects/{id}/remarks:
    post:
      consumes:
      - multipart/form-data
      description: Upload a remarks file to a specific project (max 50MB)
      operationId: uploadRemarks
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      - description: Remarks file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Remarks file uploaded successfully
          schema:
            $ref: '#/definitions/db.ProjectFile'
        "400":
          description: Bad request - invalid input data
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Upload remarks file to project
  /projects/{id}/remarks_clustered:
    get:
      consumes:
      - application/json
      description: Get clustered remarks result for a specific project
      operationId: getRemarksClustered
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Clustered remarks result
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad request - invalid project ID
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Remarks are still being processed
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get clustered remarks for project
swagger: "2.0"
