version: "3.9"

services:
  evaluation:
    build:
      context: ./services/evaluation
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=evaluation_db
      - DB_USER=evaluation_user
      - DB_PASSWORD=backtotheoil
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=backtotheoil
      - MINIO_SECRET_KEY=backtotheoil
      - MINIO_BUCKET_NAME=evaluation-files
      - MINIO_USE_SSL=false
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/evaluation", "-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      disable: true
    restart: unless-stopped
    networks:
      - evaluation-network

  front:
    build:
      context: ./services/front
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      - EVALUATION_API_URL=http://evaluation:8080
    depends_on:
      - evaluation
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - evaluation-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./services/front/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - evaluation
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - evaluation-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=evaluation_db
      - POSTGRES_USER=evaluation_user
      - POSTGRES_PASSWORD=backtotheoil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evaluation_user -d evaluation_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - evaluation-network
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=backtotheoil
      - MINIO_ROOT_PASSWORD=backtotheoil
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - evaluation-network

  # LLM service (закомментирован для будущего использования)
  # llm:
  #   build:
  #     context: ./services/llm
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - PORT=8080
  #     - ENVIRONMENT=development
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   restart: unless-stopped
  #   networks:
  #     - evaluation-network

networks:
  evaluation-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
